{
 "title": "CAN OBD2 SIMULATOR DATA ANALYSIS",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "GATEWAY",
    "label": "GATEWAY ID",
    "query": {
     "query": "from(bucket: \"CAN\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Can_data\")\n  |> group(columns: [\"Gateway_id\"])\n  |> distinct(column: \"Gateway_id\")\n  |> keep(columns: [\"Gateway_id\"])"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Engine speed",
   "type": "stat",
   "description": "Engine speed refers to the rate at which an engine's crankshaft is rotating. It's typically measured in revolutions per minute (RPM). This tells you how many times the engine's crankshaft completes one full rotation in one minute",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"Can_data\" and r.Gateway_id == \"${GATEWAY}\")\r\n  |> filter(fn: (r) => r._field == \"Engine_RPM\")\r\n"
    }
   ]
  },
  {
   "title": "Vehicle speed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"Can_data\" and r.Gateway_id == \"${GATEWAY}\")\r\n  |> filter(fn: (r) => r._field == \"Vehicle_Speed\")\r\n"
    }
   ]
  },
  {
   "title": "Engine coolant temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"Can_data\" and r.Gateway_id == \"${GATEWAY}\")\r\n  |> filter(fn: (r) => r._field == \"Engine_Coolant_Temperature\")\r\n"
    }
   ]
  },
  {
   "title": "Intake air temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"Can_data\" and r.Gateway_id == \"${GATEWAY}\")\r\n  |> filter(fn: (r) => r._field == \"Intake_Air_Temperature\")\r\n"
    }
   ]
  },
  {
   "title": "MAS AIR FLOW RATE",
   "type": "stat",
   "description": "Mass air flow sensors measure the air mass flowing into the engine intake. This is important for calculating the amount of fuel to add to achieve the proper air-fuel ration ",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "g/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"Can_data\" and r.Gateway_id == \"${GATEWAY}\")\r\n  |> filter(fn: (r) => r._field == \"Mass_Air_Flow_Rate\")\r\n"
    }
   ]
  },
  {
   "title": "Timing Advance",
   "type": "stat",
   "description": "Ignition timing is measured in degrees of a crankshaft rotation before top dead center (BDTC). Spark plugs need to fire at the right time, which can be achieved by advancing or retarding the timing of the engine. Timing advance means that the spark plugs are firing earlier in the compression stroke, farther from TDC(TOP DEAD CENTER)",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"Can_data\" and r.Gateway_id == \"${GATEWAY}\")\r\n  |> filter(fn: (r) => r._field == \"Timing_advance\")\r\n"
    }
   ]
  },
  {
   "title": "Throttle position",
   "type": "stat",
   "description": "In a motor vehicle the control used by the driver to regulate power is sometimes called the throttle, accelerator, or gas pedal. For a gasoline engine, the throttle most commonly regulates the amount of air and fuel allowed to enter the engine",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"Can_data\" and r.Gateway_id == \"${GATEWAY}\")\r\n  |> filter(fn: (r) => r._field == \"Throttle_Position\")\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "STFT",
   "type": "stat",
   "description": "Short-term fuel trims occur as a direct result of changes in the oxygen content of the exhaust stream. The exhaust stream is monitored by an oxygen sensor upstream of the catalytic converter, and the signal voltage it generates is directly proportional to the oxygen content of the exhaust stream. During normal operation of the vehicle, and provided the oxygen sensor is in closed loop operation, the ECU will react to changes in the composition of the exhaust stream almost instantly, hence the term, “short term fuel trim”, and it will do so several times per second.\n\nThe short-term fuel trim's purpose is to either add or subtract fuel based on how the engine is running",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"Can_data\" and r.Gateway_id == \"${GATEWAY}\")\r\n  |> filter(fn: (r) =>  (r._field == \"Short_Term_Fuel_Trim_-_Bank_1\" or r._field == \"Short_Term_Fuel_Trim_-_Bank_2\") )\r\n"
    }
   ]
  },
  {
   "title": "Oxygen sensors",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 10, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"Can_data\" and r.Gateway_id == \"${GATEWAY}\")\r\n  |> filter(fn: (r) => ( r._field == \"Oxygen_Sensor_1__A:_Voltage_B:_Short_term_fuel_trim\" or\r\n  r._field == \"Oxygen_Sensor_2_A:_Voltage_B:_Short_term_fuel_trim\"  or\r\n  r._field == \"Oxygen_Sensor_3__A:_Voltage_B:_Short_term_fuel_trim\" or\r\n  r._field == \"Oxygen_Sensor_4__A:_Voltage_B:_Short_term_fuel_trim\" or\r\n  r._field == \"Oxygen_Sensor_5__A:_Voltage_B:_Short_term_fuel_trim\" or\r\n  r._field == \"Oxygen_Sensor_6__A:_Voltage_B:_Short_term_fuel_trim\" or\r\n  r._field == \"Oxygen_Sensor_7__A:_Voltage_B:_Short_term_fuel_trim\" or\r\n  r._field == \"Oxygen_Sensor_8__A:_Voltage_B:_Short_term_fuel_trim\" )\r\n)\r\n"
    }
   ]
  },
  {
   "title": "Distance Travelled",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"Can_data\" and r.Gateway_id == \"${GATEWAY}\")\r\n  |> filter(fn: (r) => r._field == \"Distance_Travelled_with_MIL_on\")\r\n"
    }
   ]
  },
  {
   "title": "Engine load",
   "type": "stat",
   "description": "Engine load is essentially answering the question of how much air is going into the cylinder per combustion event relative to how much air it would ingest",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"Can_data\" and r.Gateway_id == \"${GATEWAY}\")\r\n  |> filter(fn: (r) => r._field == \"Engine_Load\")\r\n"
    }
   ]
  },
  {
   "title": "LTFT",
   "type": "stat",
   "description": "Long-term fuel trims are measured over longer time intervals by oxygen -, or air fuel ratio sensors downstream of the catalytic converter, and in practice, the signal voltages these sensors generate are not directly implicated in fuel delivery strategies, although there some exceptions to this rule\nlong-term fuel trim adds or subtracts fuel based on a trend the ECM sees",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"Can_data\" and r.Gateway_id == \"${GATEWAY}\")\r\n  |> filter(fn: (r) => (r._field == \"Long_Term_Fuel_Trim_-_Bank_1\" or r._field == \"Long_Term_Fuel_Trim_-_Bank_2\") )\r\n"
    }
   ]
  },
  {
   "title": "Evaporative System Vapor Pressure",
   "type": "stat",
   "description": "The EVAP system is designed to stop fuel system fumes from leaking directly into the atmosphere",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"Can_data\" and r.Gateway_id == \"${GATEWAY}\")\r\n  |> filter(fn: (r) => r._field == \"Evaporative_System_Vapor_Pressure\")\r\n"
    }
   ]
  },
  {
   "title": "Intake Manifold Pressure",
   "type": "stat",
   "description": "Manifold Pressure (MP) refers to the air pressure within the engine's intake manifold. Essentially, it measures the air pressure available to draw into the cylinders during the intake phase",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pressurekpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"Can_data\" and r.Gateway_id == \"${GATEWAY}\")\r\n  |> filter(fn: (r) => r._field == \"Intake_Manifold_Pressure\")\r\n"
    }
   ]
  },
  {
   "title": "Catalyst Temperature",
   "type": "stat",
   "description": "a catalytic converter filters out harmful byproducts in the exhaust gases and burns them up. And while the main function of a catalytic converter is to reduce harmful emissions, it also improves your car's efficiency.",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"Can_data\" and r.Gateway_id == \"${GATEWAY}\")\r\n  |> filter(fn: (r) =>  (r._field == \"Catalyst_Temperature_Bank_1:_Sensor_1\" or r._field ==  \"Catalyst_Temperature_Bank_2:_Sensor_1\") )\r\n"
    }
   ]
  },
  {
   "title": "Fuel pressure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurekpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"Can_data\" and r.Gateway_id == \"${GATEWAY}\")\r\n  |> filter(fn: (r) => r._field == \"Fuel_Pressure\")\r\n"
    }
   ]
  },
  {
   "title": "Barometric pressure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "atm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"Can_data\" and r.Gateway_id == \"${GATEWAY}\")\r\n  |> filter(fn: (r) => r._field == \"Barometric_Pressure\")\r\n"
    }
   ]
  },
  {
   "title": "Commanded Throttle Actuator ",
   "type": "stat",
   "description": "The throttle actuator is usually a DC motor that helps rotate certain parts precisely and efficiently\n\nActuators work behind the scenes in vehicles to convert energy into a physical action or force. They perform a variety of performance and convenience functions, from controlling the throttle to directing airflow in the climate control system, and operating power seats and liftgates",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"Can_data\" and r.Gateway_id == \"${GATEWAY}\")\r\n  |> filter(fn: (r) =>  r._field == \"Commanded_Throttle_Actuator\" )\r\n"
    }
   ]
  },
  {
   "title": "Control Module Voltage",
   "type": "stat",
   "description": "Control Module Voltage is the battery voltage, minus any volts drop in the wiring between the battery and the ECU",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"Can_data\" and r.Gateway_id == \"${GATEWAY}\")\r\n  |> filter(fn: (r) => r._field == \"Control_Module_Voltage\")\r\n"
    }
   ]
  },
  {
   "title": "Commanded EGR",
   "type": "stat",
   "description": "Exhaust gas recirculation (EGR) is an effective strategy to control NOx emissions from diesel engines. The EGR reduces NOx through lowering the oxygen concentration in the combustion chamber, as well as through heat absorption.\n",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"Can_data\" and r.Gateway_id == \"${GATEWAY}\")\r\n  |> filter(fn: (r) => r._field == \"Commanded_EGR\")\r\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 20 },
   "options": {
    "content": "<img src=\"https://www.most2414.com/wp-content/uploads/2019/04/Most2414-Services-Digital-Strategy-KPI-Business-Intelligence-1.0.png\" alt=\"No image\" width=\"200\" height=\"150\">\n<h4 style=\"color:white\">\n  CLICK HERE FOR  EXTENSIVE \n  <br>\n  VISUALIZATION\n</h4>"
   }
  },
  {
   "title": "Fuel System Status",
   "type": "stat",
   "description": "The fuel system status in a vehicle typically refers to the condition and operation of the components responsible for storing, delivering, and managing fuel to the engine. This includes the fuel tank, fuel pump, fuel lines, fuel injectors (or carburetor), fuel filter, and sometimes fuel pressure regulators and sensors",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"Can_data\" and r.Gateway_id == \"${GATEWAY}\")\n  |> filter(fn: (r) => r._field == \"Fuel_System_Status_\")\n"
    }
   ]
  }
 ]
}